### ISSUE TITLE
Include original BSD license text

### ISSUE THREAD

**Issue by cxong** [iamOgunyinka/tinydircpp#2]
Thanks for your work on porting tinydir! However, I've noticed that `tinydircpp.h` no longer has the original BSD license text. Please include this text, specifically the [lines here](https://github.com/cxong/tinydir/blob/master/tinydir.h#L2-L23) must be reproduced in the source code, as this is required by the [license](http://www.linfo.org/bsdlicense.html).

**Comment by iamOgunyinka** [comment]
Done!

**Comment by cxong** [comment]
:+1: thanks!
